export default {
  h1: {
    fontFamily: "'Roboto Condensed', sans-serif",
    lineHeight: "50px",
    wordWrap: "break-word",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "35px",
    "@media (max-width:767px)": {
      fontSize: "30px",
      lineHeight: "40px",
    },
  },
  h3: {
    fontFamily: "'Roboto Condensed', sans-serif",
    lineHeight: "46px",
    wordWrap: "break-word",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "30px",
    color: "#e59446",
    "@media (max-width:767px)": {
      fontSize: "25px",
      lineHeight: "40px",
    },
  },
  h4: {
    fontFamily: "'Roboto Condensed', sans-serif",
    lineHeight: "35px",
    fontStyle: "normal",
    wordWrap: "break-word",
    fontWeight: "500",
    fontSize: "25px",
    color: "#e59446",
    "@media (max-width:767px)": {
      fontSize: "25px",
      lineHeight: "40px",
    },
  },
  h5: {
    fontFamily: "'Mulish', sans-serif",
    lineHeight: "30px",
    fontStyle: "normal",
    wordWrap: "break-word",
    fontWeight: "300",
    fontSize: "22px",
    color: "#fff",
    "@media (max-width:767px)": {
      fontSize: "15px",
      lineHeight: "25px",
    },
  },
  h6: {
    fontFamily: "'Mulish', sans-serif",
    lineHeight: "30px",
    fontStyle: "normal",
    wordWrap: "break-word",
    fontWeight: "500",
    fontSize: "17px",
    color: "#fff",
  },
  overline: {
    fontWeight: 500,
  },
  button: {
    textTransform: "capitalize",
    borderRadius: 27,
  },
  body2: {
    fontWeight: 300,
    fontSize: "15px",
    lineHeight: "28px",
    wordWrap: "break-word",
    color: "#fff",
    fontFamily: "'Roboto Condensed', sans-serif",
  },
};
